### ISSUE TITLE
Should detect be considered public API?

### ISSUE THREAD

**Issue by wbinnssmith** [lancedikson/bowser#104]
It looks like `_detect` is exposed for testing bowser, and obviously it's indicated as private via the underscore. I imagine bowser could be useful for use in node where you could give it UA strings to parse, rather than having it grab the document's, in the case of the browser. 

Of course if you feel that bowser is a browser-exclusive module I understand. There are, after all, other modules that detect _more_ than bowser does, but I appreciate its leanness.

**Comment by jasonkarns** [comment]
Agreed. We use `_detect` within a wrapper so that we can run our tests in node. But we'd also like to use bowser full-force in node.

Would a PR be accepted that changes the api to accept a UA string and only defaults to using the `navigator`?

**Comment by lancedikson** [comment]
Sorry, guys, but I haven't got what you want to do with the API. Could you give me more details?

**Comment by jasonkarns** [comment]
Personally, I would love to see something like how substack's [cookie-cutter](https://github.com/substack/cookie-cutter/blob/master/index.js) handles it's document.cookie.

https://github.com/substack/cookie-cutter/blob/master/index.js#L1-L4

The module exports a function that, if given a string uses the string as `document.cookie`. If given an object, it treats the object as `document` (and thus expects it to have a `cookie` property; defaulting `cookie` to `""` if it doesn't). If it's given a falsey value (`undefined` being the only falsey value we really care about), it defaults to checking the global `document`. If global document doesn't exist, it falls back to `{cookie:""}` as the `document`.

For bowser, I would expect to see:

```
browser = require('bowser');

// defaults to document.navigator
browser()

// uses provided document.navigator object
browser({navigator: { userAgent: "foo"} })

// uses provided string as the ua string
browser("Mozilla/5.0 (Linux; Android 5.1.1; Nexus 9 Build/LMY48T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Safari/537.36")
```

**Comment by lancedikson** [comment]
Interesting point. I think this is a good issue for the next major release 👍  It would be nice if you want to help with it by PR? If you do, please, checkout `develop` branch and send the PR.

**Comment by lancedikson** [comment]
API of the new version will be much better. The release is very soon. You can track activity in the branch named `v2`.
