### ISSUE TITLE
Feature Request: os

### ISSUE THREAD

**Issue by charlierudolph** [lancedikson/bowser#149]
Similar to `bowser.name` being the name of the browser (which is also available via a flag), I would like there to be a `bowser.os` which is the name of the operating system. Currently I am iterating through the os flags searching for the the one that is true.

**Comment by lancedikson** [comment]
Yeah, I've been thinking to add the feature. Feel free to send me a PR with it. I could implement the feature only next week.

**Comment by peleteiro** [comment]
👍

**Comment by DaSchTour** [comment]
It would also be great if osversion would work for windows and macOS. For macOS the us string looks like this `5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12` an exposes the OS version. Windows looks like this `5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C)"` and I guess from the NT version it should be possible to get the Windows version.

**Comment by SachaG** [comment]
Similarly, couldn't we have a `device` property instead of having to iterate through all flags?

**Comment by lancedikson** [comment]
Tha feature has been released as 1.8.0

**Comment by ruluva** [comment]
Can we add the osname to the IBowserGrade interface to allows access to the osname variable? 

`export interface IBowserGrade {
        /** Grade A browser */
        a: boolean;
        /** Grade C browser */
        c: boolean;
        /** Grade X browser */
        x: boolean;
        /**A human readable name for this browser. E.g. 'Chrome', '' */
        name: string;
        /**Version number for the browser. E.g. '32.0' */
        version: string|number;
        osname: string;
        osversion: string|number;
    }`
