### ISSUE TITLE
bowser is not supporting WebRTC Calls 

### ISSUE THREAD

**Issue by Duraiamuthan** [lancedikson/bowser#164]
I tried with https://demo.openwebrtc.org from Bowser to Firefox likewise FireFox to Bowser it's not working and I even tried with https://apprtc.appspot.com but that also not working.

This makes me think whether bowser can support WebRTC.
1. http://demo.openwebrtc.io
2. http://googlechrome.github.io/webrtc/samples/web/content/getusermedia/gum
Both are down ?

Is there any other pages I can test to ensure bowser supports webrtc ?

**Comment by freefri** [comment]
I've tested Bowser here from an iPhone 5 with iOS 9.2 and it worked:
https://webrtc.github.io/samples/src/content/getusermedia/canvas/

**Comment by Duraiamuthan** [comment]
OK Ok ...this is for taking a snapshot but is there any other sample available to test webRTC Call between devices ?

**Comment by cprasmussen** [comment]
@Duraiamuthan Have done the same teste here on multiple devices, can't get video to work either.

**Comment by ibc** [comment]
Guys, this project is **NOT** about the Bowser browser at all.

**Comment by freefri** [comment]
True, I guess Google is playing with us, sorry about that. This seems to be the [right project](https://github.com/EricssonResearch/bowser)

**Comment by lancedikson** [comment]
LOL, thanks @ibc for explaining what's going on here :)
