### ISSUE TITLE
OS-specific checks

### ISSUE THREAD

**Issue by Payetus** [lancedikson/bowser#175]
I'm developing and web app with webrtc and there are certain browser versions that do not work. But it also depends greatly on the OS behind it, so the same browser version may work on Android but fail on iOS. I prupose to add some depth to the check function.

Right now we call the check function like so:

bowser.check({chrome: "51", firefox: "48"}, true , window.navigator.userAgent)

Maybe a way to make it happen would be 

bowser.check({windows:{chrome: "51", firefox: "48"}, ios:{chrome:"56"}}, true , window.navigator.userAgent)

**Comment by lancedikson** [comment]
Sounds good and makes sense 👍  Can't promise something right now, but will try to find time to implement it.

**Comment by lancedikson** [comment]
It's been released in 2.0.0-alpha.1
