### ISSUE TITLE
New 2.0 version is coming

### ISSUE THREAD

**Issue by lancedikson** [lancedikson/bowser#177]
Hi, guys. The new version is on its way. I'm gonna publish a branch with the code. So, now there is a possibility to add some new features in it. If you have some ideas, feel free to propose them here 😺

**Comment by hveveris** [comment]
**desktop** flag would be great ;)

**Comment by olgaivanysko** [comment]
Have found that `bowser.msie || bowser.msedge` returns `undefined` instead of `false` in Chrome.
Is this default behavior?
Thank you :)

**Comment by lancedikson** [comment]
Hi, @olgaivanysko. Yes, this is the default behavior. It will be fixed in the major release. Now I recommend to compare properties with `true` :)

**Comment by ibc** [comment]
I would like the ability to refresh `bowser` internals by providing a UA string, so new flags are set, etc.

To show what I mean, imagine this is Node.js environment (so not a real browser) but I want, for dark reasons, to make `bowser` behave as this is Chrome 59, so later, other JS libs checking `bowser.name === 'Chrome'` would get `true`.

```js
var bowser = require('bowser');

bowser.chrome
// => false

// Assume this new API
bowser.reset("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36");

bowser.chrome
// => true

bowser.version
// => '59.0'
```

I know that `bowser._detect(ua)` provides basically the same, but what I mean is about making `bowser.chrome` return `true` in the above case (rather than having to inspect the object returned by `bowser._detect()`).

**Comment by levithomason** [comment]
As a counterpoint, many consider [side-effects to be evil](https://softwareengineering.stackexchange.com/questions/15269/why-are-side-effects-considered-evil-in-functional-programming).  It would be nice if the functions were pure and did not have side-effects such as mutating the `bowser` object.

I personally prefer the functional approach, returning a new flags object for each detection.

**Comment by lancedikson** [comment]
@levithomason, I totally agree. It will be done in that way — a new parsed object on each request. It's already done in that way in the 2.0 version branch. I'm about to finish working on it soon and release the next major version.

**Comment by levithomason** [comment]
Superb, looking forward to it.

**Comment by toomuchdesign** [comment]
Hi @lancedikson! Thank you for the great job here.
I'd like to join the discussion to share an idea.

Since you're about to release a breaking major release, it might be interesting to find an easy way to make `bowser` and [browserslist](https://github.com/ai/browserslist) work together.

`browserlist` output looks like this:
```
and_chr 59,and_ff 55,and_qq 1.2,and_uc 11.4,android 56,android 4.4.3-4.4.4,baidu 7.12,bb 10,bb 7,chrome 61,chrome 60,edge 15,edge 14,firefox 55,firefox 54,ie 11,ie_mob 11,ios_saf 10.3,ios_saf 10.0-10.2,op_mini all,op_mob 37,op_mob 12.1,opera 47,opera 46,safari 10.1,safari 10,samsung 5,samsung 4
```
One might option might consist of uniforming browser names to browserlist ones. Or providing an adapter/bridge to easen the communication between them.

Just an idea, I still making my mind about this. Cheers!

**Comment by levithomason** [comment]
I would love this! I almost integrated it myself in https://github.com/levithomason/canibrowse.now.sh.

**Comment by maxx07** [comment]
Hi @lancedikson,
when do you think you will release the first 2.0 version?

**Comment by peteboere** [comment]
On suggestions for v2

* Project needs eslint
* Should factor out optimization oddities like `t = true`

**Comment by Offirmo** [comment]
NUMERICAL browser versions would be nice. No need to be exact, the closest major would be enough.

Ex. Chrome '66' => 66
Ex. IE9 '9.0' => 9

That would normalize versions and helps a lot for comparison / reporting / classification.

Nice to have:
If by some chance a browser reports a minor (is there any?), it could be used as a decimal, for ex. '9.1'

**Comment by lancedikson** [comment]
Hi guys. Sorry for being quiet for so long. I had some troubles in my life with arranging personal and working stuff. Now I came back into the active development of the library.

So, good news, the scope for [2.0.0-alpha.1](https://github.com/lancedikson/bowser/projects/1) is defined and almost finished already. I'm expecting this week we will have published the first alpha version, which is quite stable with its features (as I believe). The only reason to have alpha first is to propose current feature set and API to the community, listen to the comments and fix something that might be not perfect in the upcoming release. However, please, at least have a look at the new version and even try to use it.

I tried to make the code as much simple as it can be for the community to support, to make any changes and propose them. I'll highly appreciate any comments on the code parts from the collaboration point of view. Is it now convenient enough to propose PRs with browser detection fixes, like adding new browsers or platforms, or there is something to improve?

The last things I have to do before the release is the documentation and adjust building process. So, I think it shouldn't take too much time. I'll post updates here. The next update will be opened PR for this `v2` branch.

One last thing, if you have enough time and inspiration, please join me on this project. I think, we have plenty of stuff to do, from code review to the web page with bowser inside, which could help to test some user-agent string with the last Bowser version right in a browser. I'd like Bowser to have a supportive community with a couple of collaborators, who can apply some quick fixes without me and help with arranging issues.

Have a nice one, and see you in the comments section around the upcoming release 🎉

**Comment by lancedikson** [comment]
So, the 2.0.0-alpha is here. Try it, leave your feedback and bug reports in separate issues :)
