### ISSUE TITLE
Safari in iOS 11 preview is detected as version 10

### ISSUE THREAD

**Issue by zdila** [lancedikson/bowser#180]
Safari on iOS 11 preview is detected as version 10 and it should be 11. User agent string is: `Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.21 (KHTML, like Gecko) Version/10.0 Mobile/15A5278f Safari/602.1`

**Comment by lancedikson** [comment]
@zdila, AFAIK, Safari's version could be detected by `Version/xx.x` string. Maybe they have some experimental build there, so they still didn't change the UA string. Regarding the string I'd say that it's still Safari 10 :)
