### ISSUE TITLE
remove typings.d.ts?

### ISSUE THREAD

**Issue by crazyx13th** [lancedikson/bowser#182]
hi there!

normally I install typings from `@types` (´npm i `@types/bowser` --save-dev´). But then I have 2 different definition files for typescript: `@types/bowser` and `node_modules/bowser/typings.d.ts`

I can't compile without warning because he uses the typings.d.ts
![grafik](https://user-images.githubusercontent.com/8912561/27725848-768fe0e6-5d78-11e7-9a27-9eba6fc3e03e.png)
![grafik](https://user-images.githubusercontent.com/8912561/27725609-68f8fafe-5d77-11e7-96fe-6cc7e54c087a.png)

I had to delete this file (or exclude, but how?)

thanks!

https://github.com/lancedikson/bowser/blob/master/typings.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bowser/index.d.ts

**Comment by lancedikson** [comment]
Hi @crazyx13th,

Thanks for the report. I don't actually use TS in my everyday life, so I haven't been using bowser with TS. But I think that it's better to have bowser's own `typings.d.ts` according to with logical way of managing the library — changed API, change the typings here. I wouldn't go anywhere to make a PR with updated typings declaration to a separated repo with more than a hundred of open PRs, coz it's not cool at all.

So, I offer you to make some needed changes in the bowser's own typings declaration to make it satisfying requirements of an API and do not delete the file. What do you think?

**Comment by schmuli** [comment]
@crazyx13th Please see #185 which updates your type definitions.

Using type definitions from DefinitelyTyped is now officially supported by TypeScript. All type definitions are automatically published to NPM under the `@types/*` scope, and TypeScript has built-in support for locating and using any type definition files found in `node_modules/@types/*` folders.

Additionally, DefinitelyTyped is a community-supported project, meaning that anyone can contribute a PR that updates an existing type definition, or creates a new one. There is a concept of an owner, which is used for automatically requesting feedback on any update. These PRs are merged very quickly into master, and published to NPM automatically.
