### ISSUE TITLE
Some thinkpad laptops devices which are touch detects at tablet

### ISSUE THREAD

**Issue by daneshka** [lancedikson/bowser#183]
Template to report about browser detection issue

`window.navigator.userAgent` of the browser is: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Tablet PC 2.0; rv:11.0) like Gecko

 And it's detected like a Tablet
 But real device is Laptop

More resources:
[https://webmasters.stackexchange.com/questions/28569/why-would-an-ie8-in-a-desktop-has-a-tablet-pc-2-0-in-its-user-agent-string](https://webmasters.stackexchange.com/questions/28569/why-would-an-ie8-in-a-desktop-has-a-tablet-pc-2-0-in-its-user-agent-string)

[https://msdn.microsoft.com/en-us/library/windows/desktop/ms700675(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms700675(v=vs.85).aspx)

Solutions:
1) Simply not to detect Tablet PC as a tablet because they are more PC than a tablet 😃  (I think it's a marketing approach by Microsoft)
2) Set tablet to true and have another property to show it's also PC/laptop
3) Close this Issue without change.
    please don't do that. lots of my clients are now complaining they have weird tablet view on their laptop.

**Comment by lancedikson** [comment]
Sorry for the absence. I'll merge the PR today and make a new release.

**Comment by chrisforrence** [comment]
Just as a heads up, I think this issue has cropped back into 2.0.x

## Input:
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; InfoPath.3; rv:11.0) like Gecko

## Output (parsedResult):

```
{
    "browser": {
        "name": "Internet Explorer",
        "version": "11.0"
    },
    "os": {
        "name": "Windows",
        "version": "NT 10.0",
        "versionName": "10"
    },
    "platform": {
        "type": "tablet"
    },
    "engine": {
        "name": "Trident",
        "version": "7.0"
    }
}
```

**Comment by lancedikson** [comment]
@chrisforrence, thanks for the heads up :)
