### ISSUE TITLE
Fail to detect WebOS

### ISSUE THREAD

**Issue by yoonsy** [lancedikson/bowser#186]
`window.navigator.userAgent` of the browser is: `Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager`  
 And it's detected like a **chrome**  
 But real name of the browser is **webos**  

---

According to [WebOS developer site](http://webostv.developer.lge.com/discover/specifications/webos-tv-platform/web-engine/), user agent of LG webOS TV includes **Web0S**, not **WebOS**. So, the [regex for webos](https://github.com/lancedikson/bowser/blob/master/src/bowser.js#L39) should be fixed.

The '0' character of 'Web0S' is a numeric character. It's not a alphabet. I can not understand why didn't use alphabet 'o'.

**Comment by lancedikson** [comment]
Oh, good catch! Thanks for the report. I'll take care of it today.
