### ISSUE TITLE
Can we an an ID property?

### ISSUE THREAD

**Issue by bluepnume** [lancedikson/bowser#189]
Right now we can get the browser name with `bowser.name`. Or we can check if we're in a particular browser with e.g. `bowser.chrome`.

But would it be possible to add an `id` field, like `id: 'chrome'` with the alphanumeric browser name? Having this is useful vs the human-readable field, for logging, checking things like `config.ENABLED_BROWSERS[bowser.id]`, etc. In these cases using the human-readable label feels like it could be error prone in case the value ever changes, or anything like that.

Please let me know if this would be ok, and I can PR it in.

**Comment by lancedikson** [comment]
@bluepnume, yeah, I agree that it's better to have some property with the name of the browser. The fix is already in the next preparing release and will be released soon (v2.0 on its way).

**Comment by lancedikson** [comment]
Close since it duplicates #188

**Comment by bluepnume** [comment]
Awesome, thanks @lancedikson! Love the library by the way, really nice work.
