### ISSUE TITLE
Firefox Focus (Android) detected as Chrome

### ISSUE THREAD

**Issue by ibc** [lancedikson/bowser#191]
> `window.navigator.userAgent` of the browser is:

Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/1.2.1 Chrome/59.0.3071.125

>  And it's detected like a:

* `bowser.name` // => Chrome
* `bowser.version' // => 59

> But real name of the browser is ...

May be "Firefox Focus"?

https://www.mozilla.org/en-US/firefox/focus/

**Comment by lancedikson** [comment]
Good catch, @ibc! Thank you. I'll add detection of Focus soon.

**Comment by ibc** [comment]
Thanks. Said that, I feel your paint. I just cannot believe that in 2017 a new browser comes with yet such an abominable User-Agent string.
