### ISSUE TITLE
Android 8, Chrome 60 detection bug

### ISSUE THREAD

**Issue by timocov** [lancedikson/bowser#193]
`window.navigator.userAgent` of the browser is: `Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR6.170623.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.107 Mobile Safari/537.36`
 And it's detected like a `Opera`
 But real name of the browser is `Chrome 60`

**Comment by jasonpang** [comment]
- Nexus 6P Android 8.0.0 Chrome 60:
  - Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR6.170623.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.107 Mobile Safari/537.36

- Nexus 6P Android 7.1.2 Chrome 60
  - Mozilla/5.0 (Linux; Android 7.1.2; Nexus 6P Build/N2G48B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.107 Mobile Safari/537.36

- Mac OS X Chrome 60:
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36/

**Comment by jasonpang** [comment]
@lancedikson Added PR #195 to fix this.

**Comment by lancedikson** [comment]
@jasonpang, awesome, thanks! I'll have a look on it today :)

**Comment by campwise** [comment]
I upgraded to bowser-1.7.3 but I am still getting an Opera detection on Nexus 5X, am I missing something?

**Comment by lancedikson** [comment]
@campwise, do you know the UA string of that browser? That would help me to figure out what's going on.

**Comment by campwise** [comment]
Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR4.170623.009) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36

**Comment by lancedikson** [comment]
@campwise, fine, I've run a test and the UA is being detected correctly on 1.7.3. Also, have a look at the test case for Bowser: https://github.com/lancedikson/bowser/blob/04ece2212da7f3d0bca8c3073568f9a21cacd805/src/useragents.js#L10 It's quite similar to your one and it recognizes the browser as Chrome.

It seems that you might have an older version of Bowser in production or maybe that browser have cached your JS with an older version of Bowser and uses every time now. Have you tried to invalidate cache?

**Comment by campwise** [comment]
Hmmm. I must be missing something somewhere. Have cleared all cache, tried a few different browsers, have even added the string to my desktop chrome emulator but still get Opera detection. If I figure it out I'll reply back. Thanks.

**Comment by campwise** [comment]
Downloading and upgrading to 1.8.0 fixes my issue. I downloaded the 1.7.3 from the releases page at https://github.com/lancedikson/bowser/releases, is that version correct there? Thanks.
