### ISSUE TITLE
Rendering engine version

### ISSUE THREAD

**Issue by SamHH** [lancedikson/bowser#197]
At the moment the rendering engine is given back to use as `[renderingEngineName]: true`. What I think would be really useful would be if that changed to the following: `renderingEngine: { name: [renderingEngineName], version: [renderingEngineVersion] }`.

Essentially, I would like first class support for detecting by rendering engine version rather than by browser version.

IMO it makes more sense to target rendering engines which to my knowledge are the arbiters of (un)supported code, rather than the browsers which merely harness these engines. For example, instead of having to manually check my supported web standards against each version of a Blink browser (Chrome, Opera, etc) I could just check against the Blink version instead.

Would this be possible? Is this information semi-reliably provided in the same way that browser versions are?

Thanks!

**Comment by lancedikson** [comment]
Hi, @SamHH! Sorry for my absence. Yep, your idea is very good and it came to my mind recently. It's already implemented in the new upcoming 2.0 version, but I'm not sure about the first release still. I'll try to release it ASAP. It supports rendering engine in that way you described previously.

**Comment by SamHH** [comment]
That's fantastic to hear, I look forward to it whenever it's ready. 😄 Cheers!

**Comment by lancedikson** [comment]
Released in 2.0.0-alpha.1
