### ISSUE TITLE
ie11 ie10 return same version

### ISSUE THREAD

**Issue by jeongsd** [lancedikson/bowser#198]
hi i want unsupport ie version 10 and less
but ie11, ie10 both `bowser.version` return 10

### VirtualBox Win7 IE10
```js
console.log(
  bowser.msie, // true
  bowser.version, // 10
  bowser.isUnsupportedBrowser({ msie: '10' }, window.navigator.userAgent), // false
  window.navigator.userAgent, // Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)
);
```
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)

### VirtualBox Win7 IE11
```js
console.log(
  bowser.msie, // true
  bowser.version, // 10
  bowser.isUnsupportedBrowser({ msie: '10' }, window.navigator.userAgent), // false
  window.navigator.userAgent, // Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)
);
```
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)

**Comment by lancedikson** [comment]
Hi, @jeongsd, that's strange, but the problem is in the userAgent string from IE11. It definately says, that it's IE10 — `MSIE 10.0`. Could you please provide a screenshot of the "About" section from that browser?
Also, if you want to use `isUnsupportedBrowser` to avoid versions below 11, you should use `{ msie: '11'}` then, like in that test: https://github.com/lancedikson/bowser/blob/3ce77e9ed4aa1631f4d3371d2861cd7f652dc9b9/test/test.js#L120-L123

**Comment by jeongsd** [comment]
@lancedikson sorry for the late response

here "About" screenshot
### VirtualBox Win7 IE10
![image](https://user-images.githubusercontent.com/7903426/30943032-5597706e-a429-11e7-8624-66e5ede2fd5b.png)


### VirtualBox Win7 IE11
![image](https://user-images.githubusercontent.com/7903426/30943027-511cd5e2-a429-11e7-9a81-abcbeb109de6.png)

and I am currently using https://github.com/darcyclarke/Detect.js it work for me

**Comment by lancedikson** [comment]
@jeongsd, thanks for the screenshots, but this is really weird. How could both of them have the same userAgent strings? I barely can believe in it. Could you please double-check the IE11's userAgent string? Might it be a mistake of copy-pasting or something?

**Comment by jeongsd** [comment]
oh it's my mistake 
in my index.html has wronng code
```html
<meta http-equiv="X-UA-Compatible" content="IE=10">
```

![image](https://user-images.githubusercontent.com/7903426/31050569-9060677a-a689-11e7-857f-d0d7aa942f91.png)

i fix this change to
```html
<meta http-equiv="X-UA-Compatible" content="IE= edge">
```

thank you help me @lancedikson
