### ISSUE TITLE
Android 'Oreo' build strings causing Android Chrome to be detected as Opera

### ISSUE THREAD

**Issue by adamrabung** [lancedikson/bowser#199]
`window.navigator.userAgent` of the browser is: 
`Mozilla/5.0 (Linux; Android 8.0.0; Pixel Build/OPR3.170623.007) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36
`

 And it's detected like a Opera browser:
`{"name":"Opera","opera":true,"version":"","webkit":true,"android":true,"osversion":"8.0.0","mobile":true,"c":true}
`
 
But real name of the browser is Chrome 61.

Android build strings:
https://source.android.com/source/build-numbers

Thank you!

**Comment by lancedikson** [comment]
Hi, @adamrabung. Which version of bowser do you use? Have you seen #193? It's been fixed since 1.7.3.

**Comment by adamrabung** [comment]
I was using 1.7.2, I didn't notice 1.7.3. Is that officially released? Sorry I didn't notice #193 or #195, they didn't turn up when I searched "Oreo".

**Comment by lancedikson** [comment]
@adamrabung, yeah, it's released :) I don't always mark releases on Github as releases, but tag them all the time. Try the last version, please. I suggest you even to use `^1.7.0` dependency declaration, that will help you to get the latest version. We don't break compatibility at all before the `2.0.0` version and you will always have a fresh and stable version.

**Comment by adamrabung** [comment]
Works great, thanks for all of your work on this project! Sorry for the noise.
