### ISSUE TITLE
Edge version is EdgeHTML version not actual Edge browser version

### ISSUE THREAD

**Issue by camhart** [lancedikson/bowser#203]
![image](https://user-images.githubusercontent.com/3038809/31910913-d8b10658-b7f3-11e7-8370-606bde4ac2f0.png)
Bowser reports this as v15.15063

**Comment by everget** [comment]
@camhart Yes you're right, but there is no proper way to extract Edge' real version from UA, because this token doesnt exist.

See [Microsoft Edge UAs](https://github.com/everget/rowser/blob/master/data/browsers/microsoft-edge.js)

**Comment by lancedikson** [comment]
I guess this could be closed. @camhart feel free to ask any questions if you still need help.
