### ISSUE TITLE
Browser versionis undefined in standalone mode in ios.

### ISSUE THREAD

**Issue by YanBess** [lancedikson/bowser#204]
There is no **browser version** in standalone mode (app mode) in iOS (10.3.3)
Thanks.

**Comment by ibc** [comment]
@YanBess, just wondering why you ignored the issue template when reporting this undocumented issue. The issue template is clear:

> Template to report about browser detection issue
>
> `window.navigator.userAgent` of the browser is: ... 
> And it's detected like a ...
> But real name of the browser is ...

You should respect the rules for reporting issues.

**Comment by nicgirault** [comment]
Same issue.

Here is the userAgent: `Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60`.

bowser._detecct(ua) returns:

```javascript
{ 
  "name":"Safari",
  "safari":true,
  "webkit":true,
  "ipad":true,
  "ios":true,
  "osname":"iOS",
  "osversion":"10.3.3",
  "tablet":true,
  "a":true
}
```

No version here. I use bowser 1.9.3

**Comment by lancedikson** [comment]
Oh, now I had a closer look at those UAs, that you've provided and it seems that there is no way for bowser to detect versions at all. They are not provided by the browser itself, so bowser can't deal with that either. Sorry. But, if you have any idea how to fix that, come back and share, please :)

**Comment by lancedikson** [comment]
So, I'll close the issue for now, and will leave the issue about FB browser, since it's a bit simpler case, where we can detect standalone mode and say about that.
