### ISSUE TITLE
Mobile Safari Standalone Mode

### ISSUE THREAD

**Issue by beloi** [lancedikson/bowser#208]
Hello,

The browser version is not set when I'm viewing in standalone mode (iOS Mobile Safari; then add to home screen).

`window.navigator.userAgent` of the browser is:

> Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1

`window.navigator.userAgent` in standalone mode is:

> Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G36

Related: #204

**Comment by deefour** [comment]
@beloi thanks for pointing this out. I was having trouble replicating the missing version in iOS Safari and forgot to check the standalone scenario.

**Comment by lancedikson** [comment]
It seems a bit obsolete, but I'm going to close this, since Bowser can't deal with such kind of problem, when the version is not provided in the User-Agent string.
