### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by WebStew** [lancedikson/bowser#223]
I see there is a TypeScript support file in the package but this doesn't see to be picked up. Is there a way to declare this in my project?

**Comment by lancedikson** [comment]
Hi, @WebStew. I've never used Bowser with TypeScript. So, it'd rather ask anybody who knows what to do. But, basically, the project contains only types declaration for TypeScript, no more.

**Comment by WebStew** [comment]
Thanks @lancedikson.
