### ISSUE TITLE
undefined is not an object (evaluating 'e.split')

### ISSUE THREAD

**Issue by alyrik** [lancedikson/bowser#243]
We catch a lot of errors in production environment. They mostly emerge in Facebook WebView on iOS: 

**browserName**: Mobile Safari UIWebView
**browserVersion**: 11.4.0
**locale**: en-US
**osName**: iOS 11.4
**time**: 2018-08-20T07:40:17.279Z
**userAgent**: Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15F79

In code: `{key:"getVersionPrecision",value:function(e){return e.split(".").length}`.

**Comment by lancedikson** [comment]
Thanks, @alyrik, haven't seen such a bug before. Do you know the stack trace of this error? It would give a bit of a clue what's going on here.

**Comment by wamujlb** [comment]
Hello. I have the same error. But this error happens on Android 8+, Chrome 68. Here is the stack:
<img width="792" alt="screen shot 2018-08-31 at 10 00 31" src="https://user-images.githubusercontent.com/14905044/44900470-ef3c9700-ad04-11e8-8f57-4171cdef1b32.png">

Also this error: `undefined is not an object (evaluating 't.split')`

Happens both on iOS and Android: 
`Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77 [FBAN/FBIOS;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/11.4.1;FBSS/2;FBCR/vfnl;FBID/phone;FBLC/nl_NL;FBOP/5;FBRV/0]`
