### ISSUE TITLE
bowser and vue.js Microsoft Edge 

### ISSUE THREAD

**Issue by amprsnd** [lancedikson/bowser#247]
Hello!
Problem with Edge and Vue.js.

```
var agent = bowser.getParser(window.navigator.userAgent)
this.agent = agent..getBrowserName()
// or
this.agent = agent.parsedResult.browser.name
console.dir(this.agent)
```

```
[Vue warn]: Error in mounted hook: "Error: The action could not be completed. Error 80020101."

found in
---> <Player> at src\components\Player.vue
       <App> at src\App.vue
         <Root>
[object Error]:
```

Windows 10
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

Chrome, Firefox, Opera and Yandex browser work fine.
Thank you!

**Comment by lancedikson** [comment]
Hi, @amprsnd. Sorry, but the problem you described doesn't have a clue to be fixed. Are there any bowser-related messages or code lines in the stack trace of the error?

**Comment by lancedikson** [comment]
@amprsnd, I'm closing the issue for now. You can reopen it if you have any further details about the issue. Thanks.
