### ISSUE TITLE
Crash on jsdom useragent

### ISSUE THREAD

**Issue by Rakiiv** [lancedikson/bowser#249]
Version is: "bowser": "=2.0.0-beta.1",
`window.navigator.userAgent` of the browser is: Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.6.2
options for satifsfies are: { chrome: '>61.0.0', safari: '>11.0' }
It crashes on using browser.satisfies with this error:

TypeError: Cannot read property 'split' of undefined
    at Function.value (...\node_modules\bowser\es5.js:1:2246)
    at value (...\node_modules\bowser\es5.js:1:2376)
    at e.value (...\node_modules\bowser\es5.js:1:18684)
    at e.value (...\node_modules\bowser\es5.js:1:18361)
...

**Comment by lancedikson** [comment]
Hi, @Rakiiv. Thanks for the report. It seems relevant to #243, which isn't fixed yet. The fix will be done by the end of this week.

**Comment by lancedikson** [comment]
The issue has been fixed in `2.0.0-beta.2`. Check it out, please.
