### ISSUE TITLE
How i can use this without require?

### ISSUE THREAD

**Issue by burhan-kun** [lancedikson/bowser#256]
Hello,

can i use this bowser package without require in manual html, js code?

Thanks.

**Comment by RUVATA** [comment]
if you write you code in ES2015/6/7 syntax - use import startament, to load library as basic JS-module

**example of import and usage:**
`
import bowser from 'bowser';

const browser = bowser.getParser(window.navigator.userAgent);
const isValidBrowser = browser.satisfies({
	mobile: {
		'Safari': '>11',
		'Chrome': '>62',
		'Firefox': '>51',
		'UC Browser': '>11',
		'Samsung Internet for Android': '>4',
		'Android Browser': '>62'
	},
	'Chromium': '>62',
	'Chrome': '>62',
	'Firefox': '>51',
	'Opera': '>49',
	'Internet Explorer': '>10',
	'Microsoft Edge': '>17',
	'Safari': '>11'
});`

**Comment by ivan-aksamentov** [comment]
@burhan-kun You can add a CDN-hosted js file to a `<script>` tag, for example from here:
https://cdnjs.com/libraries/bowser

**Comment by lancedikson** [comment]
I guess this one has been solved. Don't hesitate to reopen if necessary.

**Comment by hburgund** [comment]
I am trying to do this as well, but am getting the following error:

```
The requested module './bowser' does not provide an export named 'default'
```
I'm guessing I'm doing something simple wrong...any ideas?

**Comment by alexreg** [comment]
If I try to import the module, I get `SyntaxError: import declarations may only appear at top level of a module`. What's going on here?

**Comment by lancedikson** [comment]
@alexreg, could you please provide a piece of code where you're importing the module? Where the exception is thrown from exactly?

**Comment by alexreg** [comment]
Exactly the import statement given in the README (copy & pasted). It's thrown there at the import statement.

**Comment by lancedikson** [comment]
@alexreg, do you use it at the top level of the file? I'm not sure where the issue goes from, but do you run it on Node or browser? Do you transpile it somehow?

**Comment by alexreg** [comment]
In the browser. No transpiling. I use it at the top of a file that I import using a `script` tag.
