### ISSUE TITLE
IE11: Object doesn't support property or method 'find'

### ISSUE THREAD

**Issue by JPStrydom** [lancedikson/bowser#264]
Bowser version:
`"bowser": "2.0.0-beta.3"`

The error occurs on `bowser.getParser(window.navigator.userAgent)`

`window.navigator.userAgent` of the browser is: _"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko"_

**Comment by JPStrydom** [comment]
Would downgrading fix this issue?

**Comment by JPStrydom** [comment]
> Hi, guys. It seems that the used `.find` method is not working on IE. It's fine and the right way to fix this now is:
> 
> 1. either make your bundling system to include a polyfill for `.find` (or transpile it to `for` loop);
> 2. or try using `'bowser/bundled'` instead, it could already have a polyfill for `.find`.

It seems that option 2 did the trick 👍

**Comment by movedoa** [comment]
Why is this marked as question? Imho this is a bug, bowser should work without polyfills or other "workarounds"

**Comment by lancedikson** [comment]
@movedoa, ok, however, it works without polyfills on Node or any ES2015 compatible browser. You see, the initial goal was to keep codebase clear and understandable as much as possible and having polyfill is quite a good trade-off here, that I decided to have in bowser. I know it's hard to satisfy all the users' needs and wishes. Thus, sorry for any inconvenience, but for now this is the way bowser is being developed.

**Comment by gcor** [comment]
Often in babel-loader options exclude node_modules files.
@babel/preset-env with {useBuiltIns: 'usage'} not parse bowser and not use polyfills.

**Comment by movedoa** [comment]
@lancedikson I get that you want a clean codebase.
But usind find or not doesn't make the codebase better or worse. It is a nice to have thing.

I guess you are using other things that IE11 doesn't support but if not, please reconsider you decision.

**Comment by doublemarked** [comment]
It's surprising to me that a module specifically intended to be used across all browsers, including very old browsers, would be prioritizing "Node or any ES2015 compatible browser".

Switching to `bowser/bundled` increases our build size by ~25Kb (40%)...bleh

**Comment by lancedikson** [comment]
@doublemarked, thanks for your feedback and I know, it may look redundant for those, who use it on the client. But, for others, it's also a good library to use on server-side. So, think about having and processing any UA strings on backend — it helps a lot.
It's been a bit of a hassle when I had ES5-only version of the library. The structure became messier, it took a lot of effort to maintain that, especially when in terms of having a little spare time for open-source.
I agree, that we should try to improve the build size, maybe there're redundant polyfills in the build. I support that, but don't have enough time to take care of it now on my own. If you have any particular ideas or feel like trying to improve this part of the library, please, don't hesitate and go ahead. I'd appreciate any help on this 🙏
