### ISSUE TITLE
Microsoft edge has no "short version name" in satisfies

### ISSUE THREAD

**Issue by pegak** [lancedikson/bowser#265]
Other browsers have something like "chrome", "firefox" or "safari", but with Microsoft Edge I had to use "Microsoft Edge".
It would be better to have "edge" or at least "msedge".

**Comment by lancedikson** [comment]
Hi, @pegak. Good thought. I haven't brought aliases to the lib yet, but it's supposed to have real browser names just to avoid any confusion and have as much declarativity and simplicity as it can. But, I think at some point we could improve that and make a list of short aliases for each browser.

**Comment by willamesoares** [comment]
Hey @lancedikson, do you think this is still valid? If so, would you give us more clarification on what's the expected work for this and if you have any assumptions on how we would support aliases?
I'm willing to work on this issue, so let me know.

**Comment by lancedikson** [comment]
hi @willamesoares, glad to hear, you're willing to take this up. I don't have any specific logic in mind about that stuff, but I guess, we should have a special entity here, like `NameResolver`, which would be a map of some internal value to different aliases (shortcuts). At first, as I can see we need only one-way resolving, which would translate `msedge|ms edge` → `Microsoft Edge` for internal usage in the parser. I think that's it for now :) Of course, this resolver should contain an extending map — we can have aliases for any other browsers if we need. But, we should be careful with these aliases as they can overlap with platforms or any other names in the end, which will be confusing :)

**Comment by willamesoares** [comment]
Hey @lancedikson, I've just opened a PR #295 for implementing this.
I believe that would possibly be an initial version for what we're aiming at here. I would appreciate any feedback on that.

Thanks for the opportunity ;)

**Comment by willamesoares** [comment]
Also, I noticed a couple of preexisting ESLint errors that are currently blocking that PR. Those are mostly related to the way we export/import `Utils` methods.
I created the issue #296 for that.

**Comment by lancedikson** [comment]
Forgot to close this one after merging the PR :)
