### ISSUE TITLE
Satisfies Method Unexpected Results

### ISSUE THREAD

**Issue by daniel-nagy** [lancedikson/bowser#269]
```javascript
const bowser = require('bowser');
const { coerce, satisfies } = require('semver');

const parser = bowser.getParser('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4');

console.log(parser.getBrowser()) // { name: 'Safari', version: '10.1.1' }
console.log(parser.satisfies({safari: '>10'})); // true
console.log(satisfies(coerce(parser.getBrowserVersion()), '>10')); // false
```

Technically it is not wrong but I expected it to behave like `semver`. Why not just use `semver`?

**Comment by lancedikson** [comment]
Hi, @daniel-nagy. Good question and the first my solution for version comparison was `semver` exactly, but actually, it doesn't work well with more "precision" that just three parts, like `56.0.3051.99`. So, we have a bit specific parser here. Probably, we should consider using `<` and `>` as it used in semver. We just didn't have the tilde `~` comparison operator before one of the latest release, so the `<` and `>` were the only way to compare. We may bring semver's specification, but it would be already a breaking change. So, maybe there is no need for that now. But if the community will come and argue with that, I agree to make a change :)
