### ISSUE TITLE
Using .satisifes is it possible to use latest version - 1?

### ISSUE THREAD

**Issue by mandazi** [lancedikson/bowser#271]
Hello,

Is it possible to do something like this:
```
const browser = bowser.getParser(window.navigator.userAgent);

const isValidBrowser = browser.satisfies({
    chrome: ">latestVersion-1",
    firefox: ">latestVersion-1"  
});
```

Basically I want it to only return true if the browser they are using is the latest version or one version behind.

I am guessing I would have to figure out the latest version outside of bowser and then subtract one and then set that in the `.satisifes` json.

Was wondering if anyone was able to do something like this.

**Comment by lancedikson** [comment]
Hi, @mandazi. I'm afraid, there is no such a possibility in bowser itself, but you can try to use `caniuse-lite` for this kind of purpose. A great example of its usage can be found here: https://github.com/browserslist/browserslist/blob/master/index.js#L2. With caniuse you can be sure about releases and that they're up-to-date. The only problem may be to match aliases or browser names that use these two libraries.
If you go with it and it works for you, please, write down here about your experience. We could take it into account some improvements in that part of the library if any needed.

**Comment by lancedikson** [comment]
I hope I could help with the answer. Closing for now.

**Comment by mandazi** [comment]
Sorry I didn't get a chance to respond. Basically just have it set to a hard coded number for now. But eventually I plan to make it dynamic by checking for the latest in another job that runs separately and updates the version stored somewhere of which I will use for this.
