### ISSUE TITLE
Allow using non strict inequality in satisfies method

### ISSUE THREAD

**Issue by darkowic** [lancedikson/bowser#274]
Currently in satisfies method we can use only strict inequality
```
chrome: '>68'
```
It would be great if we can use also the soft one
```
chrome: '>=68'
```

maybe I will try to adjust it and post PR

**Comment by darkowic** [comment]
I added PR. Waiting for feedback

**Comment by darkowic** [comment]
The PR has been merged! Thank you!

@lancedikson I did not add any documentation because I was waiting for feedback. Would be great to add it.

**Comment by lancedikson** [comment]
@darkowic, no worries, I'll add something about it to the docs :)

**Comment by lancedikson** [comment]
It's been released as 2.0.0 :) Thanks for your work on this feature
