### ISSUE TITLE
Detection of users that navigate with internet.org

### ISSUE THREAD

**Issue by sebpiq-kialo** [lancedikson/bowser#279]
Probably out of scope of the library, but I thought I'd ask. 

Any plans for detecting users navigating through [internet.org / freebasics](https://en.wikipedia.org/wiki/Internet.org) ?

**Comment by lancedikson** [comment]
Hi, thanks for the answer. I haven't heard about this project before, but as I understood, internet.org is just a possibility to have free internet, so people still use widely spread browsers to browse pages, right?

**Comment by sebpiq-kialo** [comment]
Nevermind ... detection of internet.org users is pointless as they can't use JS :D
