### ISSUE TITLE
v2 missing ChromeOS platform

### ISSUE THREAD

**Issue by ffaubert** [lancedikson/bowser#286]
I'm in the process of migrating my application from v1.9.4 to v2 and noticed that ChromeOS is no longer detectable as a built in operating system.  I can work around it by using the test(/CrOS/) (which matches how v1.9.4 worked), but it this was built in like the other operating systems.

**Comment by lancedikson** [comment]
Hi, @ffaubert. Right, I can see that there's no a proper detection specification for CrOS in bowser. We could make a hot-fix for that. Do you feel like making a PR with such a functionality? It should be a piece cake putting a spec object to [parser-os.js](https://github.com/lancedikson/bowser/blob/master/src/parser-os.js) and fixing a couple of integration tests that will fail with a new spec :)

**Comment by ffaubert** [comment]
@lancedikson Sure thing.  I submitted PR #287 for that.  I also submitted PR #288 which makes the code in my app a bit cleaner.

**Comment by lancedikson** [comment]
Thanks, @ffaubert for your PRs. I've released them as 2.1.0
