### ISSUE TITLE
ESLint import/named errors in utils file

### ISSUE THREAD

**Issue by willamesoares** [lancedikson/bowser#296]
After working on a feature I noticed a couple of ESLint errors related to the `import/named` rule due to the way we export/import methods in the `Utils` class.

<img width="839" alt="screen shot 2019-02-17 at 10 46 15 pm" src="https://user-images.githubusercontent.com/6568078/52923364-2da32e00-3306-11e9-866a-e6ed98d717e3.png">

Even though that does not seem to affect current functionality, it would be great if we can get rid of those errors.

**Comment by willamesoares** [comment]
Is PR #294 aimed at solving this issue?

**Comment by lancedikson** [comment]
Hi, @willamesoares. Yes, I guess so. I'll try to have a closer look at the PR this week. Sorry for the delay

**Comment by lancedikson** [comment]
It's solved :)
