### ISSUE TITLE
Feature / documentation request: support ranges with gaps

### ISSUE THREAD

**Issue by kachkaev** [lancedikson/bowser#298]
I'd like to support Firefox versions `>=65` _plus_ the latest [ESR version](https://www.mozilla.org/en-US/firefox/organizations/) (`=60`). I.e. write something like:

```js
browser.satisfies({
  desktop: {
    firefox: "~60,>=65",
    /* ...other browsers... */
  },
})
```

I could not find any signs of this functionality in the source, but if it's already there, it'd be great to see an example in the README.

**Comment by lancedikson** [comment]
Hi, @kachkaev. Thanks for your request and apologies for a delayed response. We don't currently have such a feature. I didn't know about ESR version of Firefox before. As it seems for me, they wouldn't ship any major improvements to ESR versions (according to their webpage):

> Maintenance of each ESR, through point releases, is limited to high-risk/high-impact security vulnerabilities and in rare cases may also include off-schedule releases that address live security vulnerabilities. Backports of any functional enhancements and/or stability fixes are not in scope.

So, would you mind sharing with me more details on what's the case exactly to detect an ESR version as long as you do with the other major versions?

For now, you can start with something simple:

```js
const BrowserParser = require('bowser/src/parser.js');
const browser = new BrowserParser(someUserAgent);

if (browser.is('firefox') && (browser.compareVersion('~60') || browser.compareVersion('>=65')) {
  // do your thing
}
```

**Comment by kachkaev** [comment]
Thanks for sharing the wokardound @lancedikson – this has worked as a solution for us. I'll close this issue because of that now, but feel free to reopen if you see value in more complex version expressions like `~60,>=65`. Thanks for your work on bowser! 🙌 👍
