### ISSUE TITLE
Could you provide API documentation for version "1.9.4"?

### ISSUE THREAD

**Issue by williamku** [lancedikson/bowser#307]
Hi,
Unfortunately we are still using "1.9.4" version.  But the API doc is nowhere to be found.  Deeply appreciated if you could forward me a link for the API-Doc for version "1.9.4".
My eMail: william.w.ku@gmail.com
Thanks!
William

**Comment by lancedikson** [comment]
Hi, @williamku. I'm sorry, but we don't have proper API docs for 1.x version. The reason is more likely that 1.x version didn't have much API, just a set of flags coming from the library. You can check out the source code or README.md of 1.x branch: https://github.com/lancedikson/bowser/tree/v1.x

**Comment by williamku** [comment]
hi, @lancedikson , no problem - thanks for providing the information!
