### ISSUE TITLE
Wring detecting version of yandex browser (mobile iOS)

### ISSUE THREAD

**Issue by a-shabanov** [lancedikson/bowser#308]
Hi, @lancedikson. 

`window.navigator.userAgent` of the browser is:  

`Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 YaBrowser/19.3.3.157.10 Mobile/15E148 Safari/605.1`

 And it's detected like 

`
browser: {
    name: "Yandex Browser"
    version: "12.0"
}
`

 However, the real version of the browser is

`19.3.3.157.10`

**Comment by lancedikson** [comment]
Thanks, seems like a bug. Needs to be fixed 👍

**Comment by lancedikson** [comment]
@a-shabanov, fyi, the fix has been deployed with 2.2.0 release

**Comment by a-shabanov** [comment]
Great! Thanks, @lancedikson
