### ISSUE TITLE
Microsoft Internet Explorer no longer recognized by satisfies(...)

### ISSUE THREAD

**Issue by wojofe** [lancedikson/bowser#309]
Microsoft Internet Explorer 11 is no longer accepted by satisfies(...) when using "msie: '>=11.0'" or "msie: '11'" or anything with msie, regardless of version number. (result: undefined)

**Comment by lancedikson** [comment]
Hi, @wojofe. Short aliases are not released yet. Please, try using `.satisfies` with full names now: `"internet explorer": "11"`

**Comment by lancedikson** [comment]
Short aliases will be available in the upcoming minor version, I guess today.

**Comment by wojofe** [comment]
That would be splendid! If you make short aliases available again, please kindly provide a list detailing which short alias works for which browser. Even the accepted browser names could use a listing in the documentary I believe.

**Comment by lancedikson** [comment]
@wojofe, please try the latest version of bowser (2.2.0). It already supports short aliases for `.satisfies`. You can find a piece of documentation here: https://github.com/lancedikson/bowser#browser-names-for-satisfies

**Comment by lancedikson** [comment]
FYI: `msie` now simply `ie`
