### ISSUE TITLE
Update for the chromium powered Edge browser 

### ISSUE THREAD

**Issue by ffaubert** [lancedikson/bowser#311]
Incase you didn't see it, a preview release of the chromium version of Edge is now available for download from https://www.microsoftedgeinsider.com/en-us/download/ (Windows 10 only, for now).

This is the user-agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.48 Safari/537.36 Edg/74.1.96.24

It is unclear to me whether or not "Edg" is intentional or a typo.

**Comment by ffaubert** [comment]
Looks like "Edg" is intentional: https://blogs.windows.com/msedgedev/2019/04/08/microsoft-edge-preview-channel-details/

> User Agent String
> With Microsoft Edge adopting Chromium, we are changing our user agent string to closely resemble that of the Chromium user agent string with the addition of the “Edg” token. If you’re blocking site access on user agent strings, please update your logic to treat this string as another Chromium-based browser.
> 
> Below is the user agent string for the latest Dev Channel build of Microsoft Edge:
> 
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.48 Safari/537.36 Edg/74.1.96.24
> 
> We’ve selected the “Edg” token to avoid compatibility issues that may be caused by using the string “Edge,” which is used by the current version of Microsoft Edge based on EdgeHTML. The “Edg” token is also consistent with existing tokens used on iOS and Android. We recommend that developers use feature detection where possible and avoid browser version detection through the user agent string, as it results in more maintenance and fragile code.

@lancedikson Do you have a plan for how you want this to work in bowser?  Is this going to detect as Chrome?  As Edge?  What about how to distinguish between the old EdgeHTML edge vs the new Chromium Edge.

**Comment by lancedikson** [comment]
Hi, @ffaubert. Thanks for a heads-up. Yeah, I've heard of this release. 

I think, we shouldn't change the name of the browser, as it's not changing. The only changing things are the version of it and the rendering engine itself (from EdgeHTML to Blink). So, I believe we should keep it detected as "Edge" and make sure, that it has "Blink" as the engine when it has `Edg` in the string.
The same thing happened with Chrome (WebKit → Blink) and Opera (Presto → Blink) before, and we kept and should keep providing consistent API for people, who rely not only on the engine but on the names as well.

If you depend on rendering engine, I recommend using `engine` property from the `ParsedResult`: http://lancedikson.github.io/bowser/docs/global.html#ParsedResult
