### ISSUE TITLE
How to get browser URL

### ISSUE THREAD

**Issue by immohdali** [lancedikson/bowser#312]
I am working at electron js. I want to capture Browser URL

**Comment by lancedikson** [comment]
Hi, @immohdali. What do you mean by "Browser URL" here?

**Comment by immohdali** [comment]
I tracking user active window...and when user go to the browser I have to
capture URL from the browser

**Comment by lancedikson** [comment]
I'm afraid, it's not related to Bowser. You can take browser's URL using browser API `window.navigator.location`
