### ISSUE TITLE
Does v 2.0 support CDN loading?

### ISSUE THREAD

**Issue by cekvenich** [lancedikson/bowser#323]
I used this in v1.X as just script src.

Reading the docs, it seems now it requires modules, is that right? 
No way to script src?

**Comment by lancedikson** [comment]
Hi, @cekvenich. Yes, 2.0 is available using via CDN. Check out these ones:
https://cdn.jsdelivr.net/npm/bowser@2.4.0/
https://unpkg.com/bowser@2.4.0/
I guess, for you the `es5.js` build would work. It differs from the `bundled.js` in the sense that it doesn't include additional polyfills.

**Comment by cekvenich** [comment]
I'd feel a lot more comfortable if you included an example of via CDN in docs. Not because above is not clear, but because it(CDN load and test if the browser is old or ie11) would then be a supported 'feature'.

**Comment by lancedikson** [comment]
Yes, maybe a bit later we will add this to the docs. For now, it seems a bit redundant, I don't want to make Readme.md even more confusing :) I hope the majority are aware of these CDNs and are able to find their way to use bowser.

**Comment by cekvenich** [comment]
ftw I'll be using isJs instead of this that I used to use: until it is document that is supports es5 from a CDN. The point is to detect old stuff, not error out.
