### ISSUE TITLE
Online web app to test bowser (done)

### ISSUE THREAD

**Issue by ibc** [lancedikson/bowser#324]
Hi @lancedikson, hope you like it:

https://github.com/ibc/bowser-online

<img width="1392" alt="Screenshot 2019-05-08 at 01 57 39" src="https://user-images.githubusercontent.com/16191/57340100-b5921a80-7134-11e9-9d2a-c6ff6ea993a3.png">

<img width="1393" alt="Screenshot 2019-05-08 at 02 20 46" src="https://user-images.githubusercontent.com/16191/57340839-e889dd80-7137-11e9-9449-491fcf921223.png">

<img width="424" alt="Screenshot 2019-05-08 at 01 57 50" src="https://user-images.githubusercontent.com/16191/57340101-b5921a80-7134-11e9-93b1-a8309d91c5b1.png">

**Comment by lancedikson** [comment]
Hi, @ibc! Wow, looks fine, thank you! Sorry for the late response, I've been on vacation without the laptop. 
If you don't mind we could move it to the bowser organization, so that it would be possible to improve it for the community and publish it to Github Pages at least. What do you think?

**Comment by ibc** [comment]
Sure, I've transferred the repo to your account @lancedikson.

**Comment by lancedikson** [comment]
Great, thanks! I moved it here: https://github.com/bowser-js/bowser-online
You're a collaborator now. We can make it better together then :) I'll probably transfer this repo as well later on.

**Comment by ibc** [comment]
Great :)
