### ISSUE TITLE
browser.satisfies default case

### ISSUE THREAD

**Issue by steverecio** [lancedikson/bowser#330]
How can I add a default for the the browser.satisfies filtering function? I want to check if the browser supports animations. I tried the following but it doesn't work. Is there not a less than filter? If not then I need a default case.

```
const doesNotSupportAnimations = browser.satisfies({
    "internet explorer": "<10",
});
```

**Comment by lancedikson** [comment]
Hi, @steverecio. I didn't really understand what you meant by "a default case". If I get it right, you were trying to use `<10` and it didn't work, right? How did you test if it works or not? Your rule for `.satisfies` says that it should be `true` when the browser is exactly IE9 or below. 
Please, give me more details on what you're trying to do, it would help me to help you :)

**Comment by steverecio** [comment]
Hey, sorry for the confusion. What I wanted to do was flip the less than to greater than and add a default. Ex.

```
const isValid = browser.satisfies({
    "internet explorer": ">9",
    "default": true
});
```

Originally, I had the above without the default case but if I'm on chrome it defaults to false. Is the less than supported? I didn't see it in the docs so I just tried it out.

**Comment by steverecio** [comment]
I solved my issue. Closing for now.

**Comment by oherik** [comment]
@steverecio It's been a while, but do you remember how you solved it?
