### ISSUE TITLE
Wrong platform detection on ThinkPad

### ISSUE THREAD

**Issue by lancedikson** [lancedikson/bowser#334]
Just as a heads up, I think this issue has cropped back into 2.x

## Version:

2.1.0

## Input:
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; InfoPath.3; rv:11.0) like Gecko

## Output (parsedResult):

```
{
    "browser": {
        "name": "Internet Explorer",
        "version": "11.0"
    },
    "os": {
        "name": "Windows",
        "version": "NT 10.0",
        "versionName": "10"
    },
    "platform": {
        "type": "tablet"
    },
    "engine": {
        "name": "Trident",
        "version": "7.0"
    }
}
```

_Originally posted by @chrisforrence in https://github.com/lancedikson/bowser/issues/183#issuecomment-511958134_

**Comment by akno** [comment]
Quick fick is to update the tablet's regex to exclude tablet PC (PC with touchable screen)
in parser-platform
```
/* Tablet */
  {
    test: [/tablet(?! pc)/i],
    describe() {
      return {
        type: PLATFORMS_MAP.tablet,
      };
    },
  },
```
