### ISSUE TITLE
Script Error in Internet Explorer (IE does not Support Array.prototype.find)

### ISSUE THREAD

**Issue by ronald** [lancedikson/bowser#347]
bowser 2.5.3 in Internet Explorer
SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "find" nicht (german)
translation: object does not support method "find"

Debugger shows follwing code:
```
var t = n.default.find(function (t) {
            if ("function" == typeof t.test) return t.test(e);
            if (t.test instanceof Array) return t.test.some(function (t) {
              return e.test(t);
            });
            throw new Error("Browser's test function is not valid");
          });
```

`window.navigator.userAgent` of the browser is: "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko"
 And it's detected like: no detection => everything broken
 However, the real name of the browser is ie 11

**Comment by lancedikson** [comment]
Hi, @ronald. Please take a look at #264. In a nutshell, bowser doesn't cover old browsers' weaknesses and don't take extra polyfills in the build. If you need one, you can include it in to your build: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill

**Comment by ronald** [comment]
Ok, thanks.

I don't get the concept.
If I want to use bowser, I have to test it in all browser to find missing methods and add it using polyfills?
Even the Internet Explorer example from README.md does not work without adding an extra polyfill without knowing which one I'l need?

**Comment by lancedikson** [comment]
> If I want to use bowser, I have to test it in all browser to find missing methods and add it using polyfills?

Ideally, no. It would have been perfect if our bundling systems could detect the need for polyfill in the codebase and include it. The concept is to have more features with less code by default, and then users can apply the needed polyfills they want it to work. This too may help you to detect what kind of features there're in the code unsupported by your target browsers and include proper polyfills for it: https://github.com/jgardella/compat.

I think we should add some note to the docs and more testing in different browsers to make it obvious where it works well and where it crashes and needs additional polyfills. But, this is an open-source product. It's not supported anyhow, so I don't have many contributors that could help me with this improvement and neither have much time for proper development of all the features.
I tried to make this lib do one thing well and be tiny enough and reusable in browser and Node — these were the main goals, compatibility was left to the users to take care by themselves.

**Comment by ronald** [comment]
Thank you very much for your explanations.

> By default, the exported version is the ES5 transpiled version, which do not include any polyfills.
This sentence from readme ist very clear but I missed the point nevertheless.
Perhaps the doc should contain: Bowser will not work in Internet Explorer by default (without polyfills)
And the following paragraph should contain: if want to use bowser inside old browsers and are not using any other polyfills you can include Bowser using bowser/bundled. And perhaps the code section should look like the first one but with bundled. 

Just my needs :-) 

Feel free to close the issue.

**Comment by lancedikson** [comment]
Yeah, I got your point. I'll try to get proper BrowserStack-based testing for the library and improve the situation with incompatible browsers as soon as I have time. For now, I'll close the issue and create a related one a bit later.
