### ISSUE TITLE
Wrong platform for IE11

### ISSUE THREAD

**Issue by akno** [lancedikson/bowser#351]
When the dectection is launch with some IE (11 in my case) on Windows 10
 `window.navigator.userAgent` of the browser is: "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; rv:11.0) like Gecko"
 And it's detected like tablet's platform
 However, the real name of the platform is desktop

The problem comes from the "Tablet PC" contains in the user agent and the detection of tablet is executed before the desktop one in the parser-platforms file

**Comment by lancedikson** [comment]
Hi, @akno. This issue duplicates #334. I got the point why it happens, thanks for your note. I'll try to fix it tomorrow. For now, I close the issue as it's a duplicate.
