### ISSUE TITLE
_bowser2.default._detect is not a function

### ISSUE THREAD

**Issue by kaytrance** [lancedikson/bowser#352]
Hello

On my mac I started to experience a weird error:

![Screenshot 2019-09-05 at 13 17 39](https://user-images.githubusercontent.com/6768891/64333657-ae462500-cfdf-11e9-8132-0fd2f3de2ead.png)

This was caused by bowser not having a specific function, so it seems, I am so frustrated:
![Screenshot 2019-09-05 at 13 15 21](https://user-images.githubusercontent.com/6768891/64333538-6921f300-cfdf-11e9-8192-78a4ff060e85.png)

I cannot even understand what is causing this. All I did is that I moved from windows based machine to mac, then removed *package-lock.json* file and *node_modules* folder and then ran `npm install`. After that my project no longer working properly and throwing this error.

Maybe someone can point out what could be the problem?

My system is: MacOS 10.14.6

**Comment by lancedikson** [comment]
Hi, it seems that you have troubles with the building of the project. I guess, you have Bowser imported as `_bowser2`, but for some reason, it thinks that it should be as `_bowser2.default`. Can you show the source code of how you're importing Bowser into that module?

**Comment by kaytrance** [comment]
I basically found a reason. It was not related to incorrect imports, but because bowser@2.x was installed that have breaking API changes. So I manually installed bowser@1.9.x and problem went away.
