### ISSUE TITLE
ES6 example in README does not work

### ISSUE THREAD

**Issue by Gudahtt** [lancedikson/bowser#353]
The ES6 example in the README does not work because there is no `default` export for the ES5 bundle. Here is the example I'm referring to:

```
import Bowser from "bowser";
```
Here is the error message I'm getting from Rollup: `[!] Error: 'default' is not exported by node_modules/bowser/es5.js`

This could be resolved either by updating the example to import from `bowser/src/bowser`, or by adding a ["module" field](https://github.com/rollup/rollup/wiki/pkg.module) to `package.json` to indicate where the ES6 entrypoint is.

**Comment by markmcdowell** [comment]
This change is resulting in an issue with our build. We now see the error `TypeError: s.getParser is not a function` using webpack to bundle. See https://github.com/helmetjs/csp/issues/89

Is there additional config now required for building?
