### ISSUE TITLE
webpack prefers "module" entrypoint in package.json over "main"

### ISSUE THREAD

**Issue by dougbrunton** [lancedikson/bowser#355]
Webpack has a feature/bug (recorded in webpack https://github.com/webpack/webpack/issues/5756) where package.json's "module" entry point is preferred over "main".

This breaks webpacked applications who depend on bowser transitively, and have no course to change the existing CJS style requires that their immediate dependencies use.

Removing bowser's "module" entry point, or adding a "browser" entry point that mimics "main" both seem avoid this class of trouble.

**Comment by lancedikson** [comment]
Wow, thanks. Let's try adding "browser" if it helps then.

**Comment by ibc** [comment]
Some good reading: https://github.com/rollup/rollup/wiki/pkg.module

**Comment by lancedikson** [comment]
I've published 2.6.1 recently with "bowser" property. Please, check it out if it fixes the issue.

**Comment by tine2k** [comment]
I am using bower in an angular application with angular cli 7.3.9 (webpack 4.29.0) and ran into this issue yesterday with 2.6.0. The new 2.6.1 fixes the problem. Thanks!

**Comment by lancedikson** [comment]
Great! Thanks for the information and sorry for any inconvenience :)

**Comment by tine2k** [comment]
Thank you @lancedikson for the very fast fix and for maintaining this great project!

**Comment by dougbrunton** [comment]
> I've published 2.6.1 recently with "bowser" property. Please, check it out if it fixes the issue.

Indeed it does.  Many thanks.

**Comment by markmcdowell** [comment]
Hmmm I've just found this but 2.6.1 didn't solve the issue. I'm using webpack 4.40.2
