### ISSUE TITLE
bowser__WEBPACK_IMPORTED_MODULE_5__.getParser is not a function

### ISSUE THREAD

**Issue by knwokolo** [lancedikson/bowser#358]
Since the new update, this has completely broken for me. When I did an npm update, I started to see this in my terminal:

"export 'getParser' (imported as 'Bowser') was not found in 'bowser'

and in the browser console, I get this:

bowser__WEBPACK_IMPORTED_MODULE_5__.getParser is not a function

I have tried reverting back but it gives another version of the same error

**Comment by lancedikson** [comment]
Hi, @knwokolo. I think it was caused by the problem described in #355. Should be fixed today.

**Comment by knwokolo** [comment]
I update to 2.6.1 and its fixed! Thank you so much!
