### ISSUE TITLE
Detect Electron

### ISSUE THREAD

**Issue by Farfurix** [lancedikson/bowser#374]
Hello,

`window.navigator.userAgent` of the browser is:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) my-app/1.0.0 Chrome/78.0.3904.113 Electron/7.1.2 Safari/537.36
```
 And it's detected like
```
{ name: 'Chrome', version: '78.0.3904.113' }
```
 However, the real name/version of the browser are
```
{ name: 'Electron', version: '7.1.2' }
```

**Comment by jamilservicos** [comment]
The script is designed to detect desktop browsers, not applications based as case of "Electron";
You can add an "Electron" block before chrome, so it will return as electron.
on file: src/parser-browsers.js

create a folder, clone it from the repository, edit as needed and install as:
npm install --save localfolder/bowser

And you will have the desired customization
