### ISSUE TITLE
Detect mobile only

### ISSUE THREAD

**Issue by hereiscasio** [lancedikson/bowser#377]
Is't possible that filter out all non-mobile devices ?

i can't find this feature in the doc

**Comment by lancedikson** [comment]
Hi, @hereiscasio. I think this should work for you: `bowser.parse(xxx).is('mobile') === false`

**Comment by hereiscasio** [comment]
@lancedikson 
sorry for the late reply.

i'll try, and let u know the result

btw, 
if i just use this plugin in frontend,
how precise it is ?

i mean, could i really filter out all the non-mobile devices ? 😶
any suggestions from u experience ?
