### ISSUE TITLE
Firefox on iPad incorrectly detected as desktop version

### ISSUE THREAD

**Issue by neckro** [lancedikson/bowser#378]
The userAgent string on Firefox/iPad is:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/21.0 Version/13.0.3 Safari/605.1.15`

This (incorrectly) parses as platform "desktop", version 21.0.

For comparison, the actual desktop Firefox/OSX userAgent is:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0`

This correctly parses as platform "desktop", version 71.0.

...and on Firefox/iPhone:
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/20.2 Mobile/15E148 Safari/605.1.15`

This correctly parses as platform "mobile", version 20.2.

This is a problem because it still reports the correct version, just the platform is wrong.  This means there's no way to properly detect this particular browser using `parser.satisfies()` -- it just looks like an old desktop version.

**Comment by lancedikson** [comment]
The fix has been released as 2.8.0. Thanks for your help and happy New Year! 👍
