### ISSUE TITLE
Wrong result in WindowsWechat

### ISSUE THREAD

**Issue by Tindtily** [lancedikson/bowser#380]
Template to report about browser detection issue

`window.navigator.userAgent` of the browser is: 

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat

 And it's detected os is Windows
 However, the real os of the browser is Mac OS
 The windows regex in src/parser-os.js should be 'windows /i' instead of 'windows/i'

**Comment by Tindtily** [comment]
The pr #381 to fix this issue

**Comment by lancedikson** [comment]
It's been fixed with the 2.8.0 release. Thanks for your help! 👍
