### ISSUE TITLE
Expected identifier in IE8

### ISSUE THREAD

**Issue by alex88** [lancedikson/bowser#412]
Just including the bundled version like this:

```
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/bowser@2.9.0/bundled.js" integrity="sha256-7HySKqxK6lLlzGjRsZJIqHsIevBojO7LA9KamStnj08=" crossorigin="anonymous"></script>
  </head>
</html>
```

throws
```
Expected identifier  bundled.js, line 1 character 997
```

I haven't seen a list of supported browsers, do you still support IE8?

Update: seems IE8 support breaks on 2.0, maybe that was expected however I haven't seen any reference to it on the changelog

**Comment by WuglyakBolgoink** [comment]
@alex88 

why we need support ie8? if ie10 already deprecated..

**Comment by alex88** [comment]
Well I imagine a lot of people use this to show deprecation warnings, but if you don't, no problem

**Comment by WuglyakBolgoink** [comment]
@alex88 It was just a question... I do not know what think plugin developers about this...

**Comment by alex88** [comment]
No worries, mine too, in fact I've ended up using the older version because I needed an easy way to detect IE < 10
