### ISSUE TITLE
Opera Mobile is detected as Chrome

### ISSUE THREAD

**Issue by zalsaud** [lancedikson/bowser#414]
User Agent: Mozilla/5.0 (Linux; Android 7.0; SM-A520F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.109 Mobile Safari/537.36 OPT/1.0.9

Its detected like this

`{
        browser: {name: "Chrome", version: "65.0.3325.109"},
        os: {name: "Android", version: "7.0", versionName: "Nougat"},
        platform: {type: "mobile"},
        engine: {name: "Blink"}
    };`

I think the reason is due to the frequent changes of Opera Mobile app name in user agent string.
Latest is Opera Touch, abbreviated as OPT, and prior to it, was Coast, Opera, Opera GX, Opera Mini, Opera Mobile, Opera Neon.

**Comment by lancedikson** [comment]
Hi, it's going to be released soon. The solution is already in master. Will release it within a few days.
