### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by lubodrinka** [lancedikson/bowser#425]
Template to report about browser detection issue
all
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /rbd/pnpm-volume/5216b8bd-af8b-4a26-acec-c681baae4d49/node_modules/.github.com/Em-Ant/fcc-express-bground-pkg/597d66d2cc536e746e1603d0332246317d515f79/node_modules/fcc-express-bground/index.js:80:26
<script src="https://cdnjs.cloudflare.com/ajax/libs/bowser/1.9.4/bowser.min.js"></script>

jquery.min.js:4 GET https://atom-earthworm.glitch.me/_api/use-env-vars 500
send @ jquery.min.js:4
ajax @ jquery.min.js:4
r.<computed> @ jquery.min.js:4
eval @ VM77:1
evalTest @ main.js:113
runTest @ main.js:80
(anonymous) @ main.js:170
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
main.js:146 Unexpected token < in JSON at position 0 Error: Unexpected token < in JSON at position 0
    at Object.eval (eval at evalTest (https://narrow-plane.glitch.me/main.js:101:14), <anonymous>:1:199)
    at j (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:29568)
    at k (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:29882)

**Comment by Uzlopak** [comment]
This seems to be totally irrelevant to bowser.

**Comment by lancedikson** [comment]
Seems so. However, @lubodrinka, the error stack trace you provided doesn't say much about the problem as you haven't provided an example of code how you're using bowser exactly. Closing it for now.
