### ISSUE TITLE
Incorrect detecting Ipad Ios 13 as mac OS Desktop in safari

### ISSUE THREAD

**Issue by Bulat94** [lancedikson/bowser#432]
Template to report about browser detection issue

`window.navigator.userAgent` of the browser is: ... 
 And it's detected like ...
 However, the real name of the browser is ...

**Comment by jaro-io** [comment]
hey @Bulat94, why did you close this? did you manage to solve it? i am having the same problem. ipad is being detected as macos. i am using the xcode simulator to test this. with all other devices (incl. iphones) it works fine.

**Comment by Bulat94** [comment]
> hey @Bulat94, why did you close this? did you manage to solve it? i am having the same problem. ipad is being detected as macos. i am using the xcode simulator to test this. with all other devices (incl. iphones) it works fine.

Hi @jaro-io, I closed the issue becouse at time it had been opened I used some simulator like xcode, and thought that the problem was in my environment but real key is settings for safari in IOS 13, which change userAgent as MacOs desktop https://www.macrumors.com/how-to/request-desktop-website-safari-for-ios/ 
My team use wraper on bowser, u can check fix commit https://github.com/AktivCo/rutoken-plugin-bootstrap/commit/45f00910ec33f81994e50bad4611b6d4a60ba540
Simple we just check touchscreen as recommended on so https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up

About reopen issue, if info above isn't helpful, could u share userAgent for template 
**window.navigator.userAgent of the browser is: ...
And it's detected like**
I will reopen it because of the pandemic now I working from home and dont have Ipad.

Hope it helps)

**Comment by jaro-io** [comment]
@Bulat94 Wow, this really helped a lot! Thank you so much! 🌾
