### ISSUE TITLE
Add support for MIUI Browser

### ISSUE THREAD

**Issue by Suaro** [lancedikson/bowser#433]
Hello,

Currently when you access from a MIUI browser, your library is returning Chrome.

The MIUI Browser user-agent can be correctly differentiated:

_Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/71.0.3578.141 Safari/534.24 **XiaoMi/MiuiBrowser/12.4.4-g**_

I understand that the output should be something similar to:

_{name: '**miui**', version: '**12 .4.4** ', os:' Android '}_

**Comment by lancedikson** [comment]
Hi, support for MiuiBrowser has been released in 2.11.0 🎉
