### ISSUE TITLE
iOS 14 on iPad is detected as macOS on Desktop

### ISSUE THREAD

**Issue by jaro-io** [lancedikson/bowser#455]
Hey @lancedikson!

This is what's being shown when using Safari's inspect on an iPad Air 4th Gen running iOS 14.

<img width="882" alt="Screenshot 2020-11-11 at 11 51 04" src="https://user-images.githubusercontent.com/20298313/98803534-378f8d80-2415-11eb-8951-3fa23fc48417.png">

`window.navigator.userAgent` of the browser is: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15`

It should be `os.name: iOS` and `platform.type: tablet`.

Thank you!

**Comment by lancedikson** [comment]
Hi, the problem is that Safari has changed their behavior here and doesn't want us to distinguish iPad from macOS. Check out #329 as this one duplicates it.

**Comment by jaro-io** [comment]
Thank you so much for the quick reply. I was thinking something like that already.. So as far as I understand, you will not implement a `touch check`? If not, I will just build that myself. ❤️

**Comment by lancedikson** [comment]
You're welcome ☺️ Yep, the point of this lib was to keep it as a UA-parser only. I'm already thinking about creating something around it 😄  but yeah, you'd better do it yourself for now.

**Comment by jaro-io** [comment]
Thanks. Yeah, let us know if you do! This library is awesome! 🦢
