### ISSUE TITLE
传统方式的项目如何使用此插件？（How to use this plug-in for traditional projects?）

### ISSUE THREAD

**Issue by WangJincheng4869** [lancedikson/bowser#491]
我目前的项目只是使用jQuery，将需要的js文件引入HTML中进行使用。项目未使用webpack。请问将如何使用？
我曾尝试引入`bundled.js`或`es5.js`无法正常使用，找不到`Bowser`对象。（我的英文不好，只能使用Google翻译）

My current project just uses jQuery, and introduces the required js files into HTML for use. The project does not use webpack. How will it be used?
I have tried to import `bundled.js` or `es5.js` which cannot be used normally, and the `Bowser` object cannot be found. (My English is not good, I can only use Google Translate)

**Comment by hellohejinyu** [comment]
![image](https://user-images.githubusercontent.com/8766034/144821847-5d836b22-946a-4ede-81eb-22b22ff351d6.png)
es5.js 亲测可以。

**Comment by WangJincheng4869** [comment]
> ![image](https://user-images.githubusercontent.com/8766034/144821847-5d836b22-946a-4ede-81eb-22b22ff351d6.png) es5.js 亲测可以。

感谢，原来如此，不能直接使用`bowser.getParser()`必须要写`bowser.getParser(window.navigator.userAgent)`
