### ISSUE TITLE
Frowser - Bowser forked 

### ISSUE THREAD

**Issue by mkkhedawat** [lancedikson/bowser#519]
Hey Everyone,

Thanks to @lancedikson for this brilliant library. But it appears it has gone busy for a good time and in the sprit of SHOW MUST GO ON, I had forked https://github.com/mkkhedawat/frowser from this project. 

Would love to have contributions and interest there.

**Comment by naorpeled** [comment]
Hey @mkkhedawat,
I love your energy and motivation, much appreciated!

Feel free to open a PR for the changes you made in your fork and I'll make sure to review and merge them 🙏
