### ISSUE TITLE
Handling of non-Linux Unix derivates?

### ISSUE THREAD

**Issue by steffen-moser** [lancedikson/bowser#526]
How does bowser handle desktop Unix derivates (e.g. FreeBSD, Solaris, Illumos/OpenSolaris) besides Linux? We might have a problem caused by bowser's behavior in BigBlueButton: https://github.com/bigbluebutton/bigbluebutton/issues/13721

**Comment by lancedikson** [comment]
Hi @steffen-moser! You can try parsing different UA-strings with bowser and see the actual results here: https://bowser-js.github.io/bowser-online/. For example, here is one of the UA strings mentioned in the issue you referenced:
`Mozilla/5.0 (X11; FreeBSD amd64; rv:94.0) Gecko/20100101 Firefox/94.0`:
![image](https://user-images.githubusercontent.com/1955931/219489050-011befd3-cc6c-489f-b178-d8827f17e030.png)
The OS stays undefined in that case.
