### ISSUE TITLE
Firefox iPad is being detected as Safari

### ISSUE THREAD

**Issue by turnipdabeets** [lancedikson/bowser#531]
From [Firefox user agent string reference - HTTP | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox), this is the UA for firefox on ipads:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

But it's being detected as `Safari`

I'm using `"bowser": "^2.11.0",`

Inspecting `Bowser.parse(window.navigator.userAgent)` on an iPad Pro 16.3.1 shows the information looks exactly the same as on a Firefox browser or a Safari browser.
![IMG_0015](https://github.com/lancedikson/bowser/assets/11654201/24044e33-089c-4d70-9ea0-9ba8dd1a69a6)
![IMG_0014](https://github.com/lancedikson/bowser/assets/11654201/02fc20b7-fd98-4638-a30d-0d964bc0cbdd)

**Comment by naorpeled** [comment]
Hey @turnipdabeets,
thanks for opening this issue.

Will try to investigate this tomorrow 🙏
will keep you posted

**Comment by naorpeled** [comment]
Seems like there's an open issue for this [here](https://github.com/mozilla-mobile/firefox-ios/issues/6620).
Not sure we have something to do on our end, but will keep investigating.

Thought it's worth sharing this in the meantime 🙏

**Comment by turnipdabeets** [comment]
> Seems like there's an open issue for this [here](https://github.com/mozilla-mobile/firefox-ios/issues/6620). In addition, found a different thread that discusses this [here](https://discourse.mozilla.org/t/firefox-99-user-agent-issue-on-ios/95661/6).
> 
> Not sure we have something to do about it on our end 😢

Ok, thanks for looking into this!

**Comment by naorpeled** [comment]
> > Seems like there's an open issue for this [here](https://github.com/mozilla-mobile/firefox-ios/issues/6620). In addition, found a different thread that discusses this [here](https://discourse.mozilla.org/t/firefox-99-user-agent-issue-on-ios/95661/6).
> > Not sure we have something to do about it on our end 😢
> 
> Ok, thanks for looking into this!

For sure!
Feel free to ping me if you need assistance with anything else :)
