### ISSUE TITLE
Publish to CDN (cdnjs & jsDelivr)

### ISSUE THREAD

**Issue by pilwon** [lancedikson/bowser#87]
Please publish bowser to [cdnjs](https://cdnjs.com/) & [jsDelivr](http://www.jsdelivr.com/) CDNs.

**Comment by eugenyshchelkanov** [comment]
@ded cdnjs has only version 1.0.0, can you publish latest version?

**Comment by zprjk** [comment]
+1

**Comment by csvan** [comment]
+1

**Comment by adiachenko** [comment]
You can use [unpkg](https://unpkg.com/). It's like a CDN, but for npm packages.

Example: `<script src="https://unpkg.com/bowser@1.6.0/bowser.min.js"></script>`

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by lancedikson** [comment]
@jimaek, wow! Amazing! So, the example of the link to 1.6.0 will be https://cdn.jsdelivr.net/npm/bowser@1.6.0/bowser.min.js. Great! I'll add it to the docs.

**Comment by jimaek** [comment]
I'm glad you like it. Let me know if you have any questions or feedback :)

**Comment by broodjekipburger** [comment]
Latest version doesn't sync, see:
- https://cdnjs.com/libraries/bowser
- https://www.jsdelivr.com/package/npm/bowser
- https://unpkg.com/bowser@1.9.4/
Can you please fix?
Thank you

**Comment by lancedikson** [comment]
Hi, @broodjekipburger, thanks for noticing. Somehow the last version hasn't been published. I'll republish it now.

**Comment by lancedikson** [comment]
@broodjekipburger, should be fine now. Check it out :)

**Comment by broodjekipburger** [comment]
Perfect, thank you 👍
